# Adding Geospatial Information

In [42]:
data = pd.read_csv("toronto_base.csv")
data.head()

,Unnamed: 0,PostalCode,Borough,Neighborhood
0,0,M3A,North York,Parkwoods
1,1,M4A,North York,Victoria Village
2,2,M5A,Downtown Toronto,"Regent Park , Harbourfront"
3,3,M6A,North York,"Lawrence Manor , Lawrence Heights"
4,4,M7A,"Queen's Park , Ontario Provincial Government","Queen's Park , Ontario Provincial Government"

In [39]:
# import sys
# !conda install -c conda-forge geopy --yes --prefix {sys.prefix}
# !conda install -c conda-forge folium=0.5.0 --yes --prefix {sys.prefix}
# !conda install -c conda-forge geocoder --yes --prefix {sys.prefix}

In [40]:
locations = pd.read_csv("https://cocl.us/Geospatial_data")
locations.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [43]:
locations.columns = ["PostalCode", "Latitude", "Longitude"]
data2 = pd.merge(data, locations, on='PostalCode')
data2.head()

,Unnamed: 0,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,0,M3A,North York,Parkwoods,43.753259,-79.329656
1,1,M4A,North York,Victoria Village,43.725882,-79.315572
2,2,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.654260,-79.360636
3,3,M6A,North York,"Lawrence Manor , Lawrence Heights",43.718518,-79.464763
4,4,M7A,"Queen's Park , Ontario Provincial Government","Queen's Park , Ontario Provincial Government",43.662301,-79.389494

In [46]:
data2.to_csv('toronto_final.csv')